backend-1   | Found 0 relevant recipes:
backend-1   |
backend-1   | ERROR:root:Tool call failed
backend-1   | Traceback (most recent call last):
backend-1   |   File "/app/assistant.py", line 86, in chat
backend-1   |     add_recipe(attributes["recipe_yaml"])
backend-1   |   File "/app/assistant.py", line 205, in add_recipe
backend-1   |     recipe_data = yaml.safe_load(recipe_yaml)
backend-1   |   File "/root/.cache/pypoetry/virtualenvs/recipes-9TtSrW0h-py3.10/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
backend-1   |     return load(stream, SafeLoader)
backend-1   |   File "/root/.cache/pypoetry/virtualenvs/recipes-9TtSrW0h-py3.10/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
backend-1   |     return loader.get_single_data()
backend-1   |   File "/root/.cache/pypoetry/virtualenvs/recipes-9TtSrW0h-py3.10/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
backend-1   |     node = self.get_single_node()
backend-1   |   File "/root/.cache/pypoetry/virtualenvs/recipes-9TtSrW0h-py3.10/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
backend-1   |     document = self.compose_document()
backend-1   |   File "/root/.cache/pypoetry/virtualenvs/recipes-9TtSrW0h-py3.10/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
backend-1   |     node = self.compose_node(None, None)
backend-1   |   File "/root/.cache/pypoetry/virtualenvs/recipes-9TtSrW0h-py3.10/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
backend-1   |     node = self.compose_mapping_node(anchor)
backend-1   |   File "/root/.cache/pypoetry/virtualenvs/recipes-9TtSrW0h-py3.10/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
backend-1   |     item_value = self.compose_node(node, item_key)
backend-1   |   File "/root/.cache/pypoetry/virtualenvs/recipes-9TtSrW0h-py3.10/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
backend-1   |     node = self.compose_mapping_node(anchor)
backend-1   |   File "/root/.cache/pypoetry/virtualenvs/recipes-9TtSrW0h-py3.10/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
backend-1   |     item_value = self.compose_node(node, item_key)
backend-1   |   File "/root/.cache/pypoetry/virtualenvs/recipes-9TtSrW0h-py3.10/lib/python3.10/site-packages/yaml/composer.py", line 82, in compose_node
backend-1   |     node = self.compose_sequence_node(anchor)
backend-1   |   File "/root/.cache/pypoetry/virtualenvs/recipes-9TtSrW0h-py3.10/lib/python3.10/site-packages/yaml/composer.py", line 111, in compose_sequence_node
backend-1   |     node.value.append(self.compose_node(node, index))
backend-1   |   File "/root/.cache/pypoetry/virtualenvs/recipes-9TtSrW0h-py3.10/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
backend-1   |     node = self.compose_mapping_node(anchor)
backend-1   |   File "/root/.cache/pypoetry/virtualenvs/recipes-9TtSrW0h-py3.10/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
backend-1   |     while not self.check_event(MappingEndEvent):
backend-1   |   File "/root/.cache/pypoetry/virtualenvs/recipes-9TtSrW0h-py3.10/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
backend-1   |     self.current_event = self.state()
backend-1   |   File "/root/.cache/pypoetry/virtualenvs/recipes-9TtSrW0h-py3.10/lib/python3.10/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
backend-1   |     raise ParserError("while parsing a block mapping", self.marks[-1],
backend-1   | yaml.parser.ParserError: while parsing a block mapping
backend-1   |   in "<unicode string>", line 8, column 7:
backend-1   |         - name: "Dried kombu"
backend-1   |           ^
backend-1   | expected <block end>, but found '<scalar>'
backend-1   |   in "<unicode string>", line 9, column 41:
backend-1   |      ... y: "1 sheet, approximately 8.5" x 11", broken into bookmark size ...
backend-1   |                                          ^
backend-1   | {'tool_call_id': 'call_s0zCmvkVoaWgJ9W7mJizXvKP', 'output': 'Error in function call add_recipe with arguments {"recipe_yaml":"recipe:\\n  title: \\"Dashi\\"\\n  estimated_cooking_time: \\"50 minutes\\"\\n  serves: \\"Variable, based on use\\"\\n  ingredients:\\n    - name: \\"Dried shiitake mushrooms\\"\\n      qty: \\"Two handfuls\\"\\n    - name: \\"Dried kombu\\"\\n      qty: \\"1 sheet, approximately 8.5\\" x 11\\", broken into bookmark sized pieces\\"\\n  steps:\\n    - step: \\"Add dried shiitake mushrooms and kombu to water in a 4-quart pan.\\"\\n    - step: \\"Bring the water to 140 degrees F and maintain the temperature for 50 minutes.\\"\\n    - step: \\"Ensure the heat does not exceed 150 degrees F.\\"\\n  notes: \\"Use this as a base for soups or other dishes.\\""}'}
